### ISSUE TITLE
Freetrack Input?

### ISSUE THREAD

**Issue by ghost** [r57zone/OpenVR-OpenTrack#1]
Hi! I am using PsMoveService (https://github.com/cboulay/PSMoveService) for a diy headset and would like to get freetrack input (as in OpenVR-OpenTrack gets input from freetrack) with this so I dont have to use riftcat as it is too laggy. Could you add this feature? Thank you!

**Comment by r57zone** [comment]
Do I understand correctly that you want me to add support OpenTrack to PSMoveService?

**Comment by ghost** [comment]
No, I am saying you should add freetrack input to OpenVR-OpenTrack so it can be used with freetrack. Here is what I am doing: I use psmoveservice to send psmove data to freepie, then I use freepie to send that data to freetrack, then riftcat picks it up and uses that for head positional tracking and rotational tracking, since riftcat is too laggy, I would like to use your (FREE!) driver instead of riftcat so this can get the input. I will use this in combination with a free app that extends the desktop with my phone.

**Comment by r57zone** [comment]
Unfortunately, I do not plan to make other inputs. Maybe Is it possible to ask the creator of OpenTrack to create the necessary plugin?

There is also a plugin for OSVR, which allows you to use FreePie - https://github.com/simlrh/OSVR-fusion .

There is also a SteamVR driver for OSVR. Before running, must configure OSVR-core and run OSVR-server.

[OSVR_SteamVR.zip](https://github.com/r57zone/OpenVR-OpenTrack/files/1275498/OSVR_SteamVR.zip)

**Comment by ghost** [comment]
I have asked a few months ago when I just heard of this.... Still no response. I guess I will fork this and add it in myself. I'm not too good at C++ though.

**Comment by r57zone** [comment]
I will make a driver with FreeTrack support in the near future.

**Comment by r57zone** [comment]
I added a driver with FreeTrack support, also updated the readme for setup.

**Comment by r57zone** [comment]
Although no, still needs work.

**Comment by r57zone** [comment]
The driver is ready, if you check it, please write.
