### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by ghost** [r57zone/OpenVR-OpenTrack#10]
The SteamVR Settings app doesnt do anything, just complains that steam and steamvr is open, while it isnt, it is somehow tied to null driver not being in drivers folder, it doesnt matter if steam and steamvr is open, it succeeds doing nothing if null driver is present in the drivers folder, it fails and complains that steam and steamvr is open if there isnt a null driver in the drivers folder

**Comment by r57zone** [comment]
Remove SteamVR, remove folder "...\Steam\steamapps\common\SteamVR". Install SteamVR again. Restart the computer, try again install with SteamVR Settings.

**Comment by ghost** [comment]
Is there any way to do this without reinstalling SteamVR, because i get the error frequently.

**Comment by r57zone** [comment]
Manualy replace the file "driver_null.dll" in "...\Steam\steamapps\common\SteamVR\drivers\null\bin\win64" to x64 driver from [releases](https://github.com/r57zone/OpenVR-OpenTrack/releases).
