### ISSUE TITLE
Game Runs But Doesn't Track

### ISSUE THREAD

**Issue by ryanslikesocool** [r57zone/OpenVR-OpenTrack#11]
I'm pretty sure that I put everything in the correct spot and made sure that everything runs, but even if I've got tracking running with OpenTrack while the game runs, the game doesn't track my movements.  I've got the right output.  Another issue that I've tried to fix is the game running upside down and backwards.  I've added `"scanoutOrigin": "upper-left",` to the steamvr.vrsettings file but that doesn't seem to work.  Sorry if I'm not asking this is the right place.

**Comment by r57zone** [comment]
You have installed the FreeTrack driver with SteamVR settings?
You have installed OpenTrack?
You put the output FreeTrack, a input FreePie UDP receiver?
Perhaps your mistake is in the wrong IP address, in the Android application.

**Comment by ryanslikesocool** [comment]
I have installed the FreeTrack driver.  I have installed OpenTrack.  I am outputting FreeTrack and inputting the paper marker.  I am not doing anything over the internet.

**Comment by r57zone** [comment]
In OpenTrack the yaw pitch roll in game data changing?

**Comment by ryanslikesocool** [comment]
Yes, in OpenTrack the data is changing and the pink model is moving like I am.

**Comment by r57zone** [comment]
Try to completely close Steam & SteamVR with task manager or reboot system, reinstall the FreeTrack driver with SteamVR Settings.

Try then to do so as in the [video](https://www.youtube.com/watch?v=mDkdj_vn5Lk&feature=youtu.be).

**Comment by ryanslikesocool** [comment]
I've followed your instructions.  The game is no longer upside down and backwards, however, tracking still does not work, the image is lower quality, and I cannot change the camera with the controller anymore.

**Comment by r57zone** [comment]
Unfortunately, I no longer have any idea what can be done. I checked it and it works for me.

**Comment by ryanslikesocool** [comment]
Oh well.  Thank you for trying!

**Comment by r57zone** [comment]
You can also try to manually replace file "driver_null.dll" in "...\Steam\steamapps\common\SteamVR\drivers\null\bin\win64" 
https://github.com/r57zone/OpenVR-OpenTrack/releases
You can also try the UDP driver.
