### ISSUE TITLE
SteamVR tracking doesn't work with Opentrack 2.3.10

### ISSUE THREAD

**Issue by dusan-t** [r57zone/OpenVR-OpenTrack#12]
SteamVR tracking doesn't work with Opentrack version 2.3.10
I had to go back to version 2.3.9 for it to start working again.

**Comment by r57zone** [comment]
Checked with the latest version of OpenTrack. UDP and FreeTrack driver work without problems.

**Comment by dusan-t** [comment]
It's possible that it was something else that was delaying
the connection between my phone and PC, not related to the new version of
Freetrack, because it happened once with the 2.3.9 as well and a restart
helped. I will try again with the 2.3.10

**Comment by dusan-t** [comment]
So I tried again with Opentrack 2.3.10 and this time tracking in Steam VR worked but not in Tridef when using Freepie to Mouse tracking (without SteamVR). Also with 2.3.10 it takes much longer for tracking between PC and phone to start working while with 2.3.9 everything works fine.

**Comment by r57zone** [comment]
This driver has nothing to do with Tridef 3D and is not needed when using Tridef 3D.
If opentrack 2.3.9 works well, you can use it.

**Comment by r57zone** [comment]
It's working with OpenTrack 2.3.10?

**Comment by dusan-t** [comment]
SteamVR tracking worked with 2.3.10 when I tried it again, but I think I only tried it once before I installed 2.3.9 again because 2.3.10 didn't work with Tridef. Also, 2.3.10 takes longer to find connection between phone and a PC, I think this is the reason why I originally thought 2.3.10 didn't work, as it took too long to connect.  I'm on Windows 7.
