### ISSUE TITLE
OpenTrack+Pimax 4k

### ISSUE THREAD

**Issue by Durimor** [r57zone/OpenVR-OpenTrack#13]
Can you please tell me if it's possible to connect the PiMax 4K virtual reality helmet to the steam VR via OpenVR-OpenTrack.

**Comment by r57zone** [comment]
Pimax can connect a second display (extended)? If so, then it will only be necessary to understand with tracking, need write a driver reading the rotation data from Pimax or simply make a tracker based on Arduino and attach it to the HMD or Aruco Paper marker + webcam.

**Comment by Durimor** [comment]
Нет, в режиме второго экрана PiMax позволяеттолько смотреть фильмы, при
запуске игры в оконном режиме шлем в steamVR не активируется.


No, in the second screen PiMax allows only to watch movies, when starting
the game in window mode, the helmet in steamVR is not activated.

2018-06-10 14:54 GMT+03:00 Кладовая <notifications@github.com>:

**Comment by Durimor** [comment]
Вопрос, можно ли сделать посредством OpenTrack при источнике данных
PointTracker 1.1 эмуляцию на выходной интерфейс HDM Pimax?


A question, whether it is possible to make through OpenTrack at data
exhaustion PointTracker 1.1 emulation on target interface HDM Pimax?

2018-06-10 14:54 GMT+03:00 Кладовая <notifications@github.com>:

**Comment by r57zone** [comment]
Этот драйвер как раз работает с экранами, которые в режиме второго экрана. Нужно запустить "SteamVR Settings", выбрать второй монитор (номер ползунком) и установить. Должно все запуститься. 

Point Tracker будет работать без проблем, нужно запустить "OpenTrack", выбрать "Point Tracker" и в выходящий интерфейс выставить "FreeTrack" или "UDP" (в зависимости от установленного, по умолчанию FreeTrack). После чего заработает трекинг.

**Comment by Durimor** [comment]
Я как раз и пытаюсь объяснить в чём сложность при исползовании PiMax. У
шлема два режима работы:
1. Режим Кинотеатра (в этом режиме VR-шлем определяется как второй экран),
игру в этом режиме запустить можно, но будешь играть как сидя в кинотеатре
с большим монитором;
2. Игровой режим (это и есть режим с погружением в VR), но при этом режиме
VR-шлем как второй экран не определяется (поэтому ползунок в "SteanVR
Settings" не активен и находится только в одном положении 1).
При запуске OpenVR на мониторе появляется "сетка VR" и на OpenTrack она
реагирует, но сам VR-шлем (PiMax) остается не активен :(((

12 июня 2018 г., 21:51 пользователь Кладовая <notifications@github.com>
написал:

**Comment by Durimor** [comment]
I'm just trying to explain the complexity of using PiMax. The helmet has
two modes of operation: 1. Cinema mode (in this mode the VR helmet is
defined as the second screen), you can start the game in this mode, but you
will play as sitting in a cinema with a large monitor; 2. The game mode
(this is the mode with immersion in VR), but in this mode the VR helmet is
not detected as the second screen (therefore the slider in "SteanVR
Settings" is not active and is only in one position 1). When OpenVR is
started, the "VR grid" appears on the monitor and responds to OpenTrack,
but the VR-helmet (PiMax) remains inactive: (((

P.S.

Add screenshots for explanation.

Добавил скриншоты для пояснения.

12 июня 2018 г., 23:09 пользователь Pche'l . <drefanclub@gmail.com> написал:

**Comment by r57zone** [comment]
Скриншоты увы не пришли, но нужно добиться того, чтобы Pimax был просто как монитор. Может драйвера удалить, может быть Pimax center сам изменяет настройки Windows.

**Comment by Durimor** [comment]
Без запуска PiMax center и без драйверов шлем определяется как неизвестное
устройство.
Пробую ещё раз скинуть скриншоты.

12 июня 2018 г., 23:38 пользователь Кладовая <notifications@github.com>
написал:

**Comment by gomayan** [comment]
Hi  Durimor,
When using Pimax 4 К, Piplay becomes unnecessary.
Make pimax recognized as the second (or first) display of Windows.
install OpenVR OpenTrack. Seting Tracker (I used pseye & clip-pro).
Open opentrack. Check if tracking is possible.
Start stermvr.
Adjust opentrack X, Y, Z rotation to synchronize with real X, Y, Z axis.
Restart stermvr, & setup stermvr position.
Go Test your likes game.
 I was play Preject-car's free edition (view & tracking is ok). 

Note
view is Landscape, will be only 1920 x 1080.
A hand controller like VIVE can not be used. (I could not set it)
In DCS etc., confusion is caused because acquisition of rotation axis is different between menu screen and play screen.

**Comment by gomayan** [comment]
Piplay is not necessary when using Pimax.
Piplay uninstall.
Restart PC. 
Connect Pimax.
Let Windows OS recognize it as the second screen (or the first screen) landscap.
{In this case it is fixed to 1920 x 1080 only. )
Install OpenVR - OpenTrack.
Connect  tracker. (I used pseye and clip-pro)
Launch opentrack.
Start stermvr
Swap the XYZ axes of opentrack and make the XYZ axes of stermvr normal.
Seting stermvr at seated position.
Playing vr with no drift of pimax 4k.
( Preject car's free edition's Tracking succeeded with this setting.)

Note
You can not use a controller like VIVE. (I have NoloVR, but I could not make the setting.)
DCS has acquired the XYZ axis input from the same stermvr side as the menu screen Preject car's free edition's,
The play screen  XYZ axis is acquired directly from the hard side. When opening a menu on the play screen, the axis is confused and you can not select anything.

**Comment by gomayan** [comment]
Piplay is not necessary when using Pimax.
Piplay uninstall.
Restart PC. 
Connect Pimax.
Let windows OS recognize it as the second screen (or the first screen) landscap.
{In this case it is fixed to 1920 x 1080 only. )
Install OpenVR - OpenTrack.
Connect  tracker. (I used pseye and clip-pro)
Launch opentrack.
Start stermvr
Swap the XYZ axes of opentrack and make the XYZ axes of stermvr normal.
Seting stermvr at seated position.
Playing vr with no drift of pimax 4k.
( Preject car's free edition's Tracking succeeded with this setting.)

Note
You can not use a controller like VIVE. (I have NoloVR, but I could not make the setting.)
DCS has acquired the XYZ axis input from the same stermvr side as the menu screen Preject car's free edition's,
The play screen  XYZ axis is acquired directly from the hard side. When opening a menu on the play screen, the axis is confused and you can not select anything.
