### ISSUE TITLE
Can't play non-VR games in full screen

### ISSUE THREAD

**Issue by dusan-t** [r57zone/OpenVR-OpenTrack#15]
When playing non-VR games in virtual screen apps like Virtual Desktop and Bigscreen, it's impossible to play the game in full screen mode, because the moment the game enters full screen the Headset window becomes red, because Windows doesn't support running two apps in full screen on two monitors at the same time. For 2D gaming this isn't that big of a deal as you can run the game in windowed mode and for Tridef there is a registry hack that allows windowed 3D, but for Nvidia 3D Vision DirectX 11 games there is no workaround, it requires full screen in order for 3D to work. Is there anything that can be done to fix this ?
3D Vision has really good 3D support for many games, it's a real shame that it doesn't work on phone VR.

EDIT: Of course it's possible to just use Opentrack and Moonlight and stream PC desktop directly to phone, without SteamVR, but in that case head tracking is tied to mouse which is always more jittery than the SteamVR tracking and there is no virtual screen. Btw, any thoughts on why is tracking so bad when translating Freepie to mouse, while Freepie to SteamVR is fine ?

**Comment by r57zone** [comment]
I know about this problem, but I do not know how to fix it. For phone vr, it's probably better to use trinus or riftcat. There is also such a project - [openvr-custom hmd](https://github.com/sencercoltu/openvr-customhmd), but it does not have binaries and instructions. There's an picture streaming into own android application.

**Comment by dusan-t** [comment]
Trisnus doesn't support SteamVR through Moonlight, as for Riftcat, yes it could be a good solution but I had some troubles using it with Moonlight - it worked but connecting and running everything was not a smooth experience to say the least.
