### ISSUE TITLE
Uninstalling?

### ISSUE THREAD

**Issue by ButterscotchV** [r57zone/OpenVR-OpenTrack#16]
I've installed this a while back and it seems to have permanently messed up SteamVR? I can't do anything with SteamVR because of this, any way to get rid of it entirely?

**Comment by r57zone** [comment]
SteamVR Settings app replacing the config and dll drivers files in "null" folder.

Return to the old state:
1. Remove config "...\Steam\config\steamvr.vrsettings"
2. Remove folders in "...\Steam\steamapps\common\SteamVR\drivers\null\"
3. Remove SteamVR and install again.

**Comment by ButterscotchV** [comment]
Thanks, it worked 👍
