### ISSUE TITLE
DIY Headset using a HDMI screen + arduino with gyroscope

### ISSUE THREAD

**Issue by AlexTheTech** [r57zone/OpenVR-OpenTrack#17]
Hi there,
I was wondering if I was able to make my own headset using your program, the only issues is that i don't know how to use the second screen as VR headset or how to translate the Arduino Gyroscope info to Steam VR, I don't have any code I was wondering if this could be possible.
Cheers!

**Comment by r57zone** [comment]
Hi, yes. You need to buy [HDMI 5.5 display](http://ali.pub/1llt51), [Arduino](http://ali.pub/1lltzk) and [GY-85](http://ali.pub/1lltk0). Some use instead of GY-85 - MPU 6050, this is also possible, you need to draw a conclusion like Razor IMU Sketch.

Firmware for Arduino - [Razor IMU](https://github.com/Razor-AHRS/razor-9dof-ahrs)
SteamVR driver with support Razor IMU - https://github.com/TrueOpenVR/SteamVR-TrueOpenVR (after install True OpenVR - https://github.com/TrueOpenVR/TrueOpenVR-Core )

**Comment by AlexTheTech** [comment]
Hi, thanks for getting back to me,
Are you sure the Razor software works with an MPU 6050? Because they say to use either 9DOF Razor IMU or 9DOF Sensor Stick, they mention nothing about the GY-85 or MPU 6050.

Cheers!

**Comment by r57zone** [comment]
Yes, I have such a tracker. It is important that the GY 85 magnetometer is one of the list - https://github.com/Razor-AHRS/razor-9dof-ahrs/blob/master/Arduino/Razor_AHRS/Razor_AHRS.ino#L160 for the RazorIMU firmware to be compatible (magnetometer calibration).

For MPU 6050 will have to search for firmware, but it is also compatible. The driver "RazorIMUStr" reads the string format "#YPR=-103.49,2.74,4.74", and the driver "RazorIMUBin" reads the binary format of the 3 float number.

RazorIMUStr:
```
Serial.print("#YPR=");
Serial.print(TO_DEG(yaw)); Serial.print(",");
Serial.print(TO_DEG(pitch)); Serial.print(",");
Serial.print(TO_DEG(roll)); Serial.println();
```

RazorIMUBin:
```
float ypr[3];  
ypr[0] = TO_DEG(yaw);
ypr[1] = TO_DEG(pitch);
ypr[2] = TO_DEG(roll);
Serial.write((byte*) ypr, 12);
```

I'm not sure if you need an expensive GY 85 today, maybe a fairly cheap MPU 6050.

Firmware for MPU6050 https://github.com/terminal29/Arduino-Tracker-Plugin/tree/master/Arduino_Tracker_Sketch or http://www.geekmomprojects.com/gyroscopes-and-accelerometers-on-a-chip/ needs further work, need to remove the quatraion for first firmware and make the output of YPR, either binary or string like Razor IMU.

**Comment by AlexTheTech** [comment]
Sorry, I'm clueless when it comes to code, so I just have to remove the // in front of line 160?
What do I do with this code?

RazorIMUStr:

Serial.print("#YPR=");
Serial.print(TO_DEG(yaw)); Serial.print(",");
Serial.print(TO_DEG(pitch)); Serial.print(",");
Serial.print(TO_DEG(roll)); Serial.println();
RazorIMUBin:

float ypr[3];  
ypr[0] = TO_DEG(yaw);
ypr[1] = TO_DEG(pitch);
ypr[2] = TO_DEG(roll);
Serial.write((byte*) ypr, 12);

Cheers!

**Comment by r57zone** [comment]
This code is needed if you have to do your make firmware for the MPU 6050.

**Comment by AlexTheTech** [comment]
I understand that, but where do I put it? Do I add it to Razor_AHRS.ino or where do I put it in?

**Comment by r57zone** [comment]
In Razor AHRS you do not need to add anything, but it is supported as is. It needs to be downloaded to Arduino, configured and calibrated.

**Comment by AlexTheTech** [comment]
OHHHH ok makes sense now thankyou i will see if it works 👍
