### ISSUE TITLE
Performance issue, framerate drops with a gtx 1060 6GB

### ISSUE THREAD

**Issue by ghost** [r57zone/OpenVR-OpenTrack#18]
Hi,
I would first like to thank you for the work you put into this driver. I am experiencing issues where framerate seems to drop and whenever I start moving my head it seems like the lens distortion images shifts to either left or right depending on the direction I turn. I have tested the framerate using Riverturner and it reports 60fps but its not smooth. What could be the problem?
I am using a GTX 1060 6GB, 16GB Ram and Xenon E3-1240 v3 @3.4GHz turbo to 3.9GHz

**Comment by r57zone** [comment]
Hi, is this happening in all games? For me this usually happens if the game is too demanding of resources. You can try to reduce the resolution of the render, for example, at 1280 by 720, for testing.

**Comment by ghost** [comment]
This happens even in the default background of steamvr with no game loaded. The gpu load is usually around 2%. Could it be a reprojection issue? I tried downgrading the driver to 6.0 the same thing happened. There is no option to disable reprojection in steamvr beta, all there is is motion smoothing, which doesnt work.

**Comment by r57zone** [comment]
Is Debug mode not activated?

**Comment by ghost** [comment]
I finally found a fix. I removed steamvr beta and finally got an option to disable reprojection, both asynchronous and interleved. It performes better than when reprojection is on. Thanks for your support.

**Comment by r57zone** [comment]
It seems I understood why there were problems, I updated SteamVR Settings, try downloading it again and reinstalling.

The first reason was to render a picture of 90 frames per second, and this is not always necessary.

The second reason was in Async Reprojection, it slows down render, this is the setting in the updated SteamVR, now it is disabled by default. It can be enabled in the settings SteamVR -> Headset Window -> Settings.

**Comment by ghost** [comment]
Will do that, thanks.
