### ISSUE TITLE
Feature/enhancement: Please add motion smoothing support

### ISSUE THREAD

**Issue by ghost** [r57zone/OpenVR-OpenTrack#19]
Hi,
Please add motion smoothing support that was added in steam beta. It might help stabilize the framerate either on a very demanding game or on low hardware.
Thanks.

**Comment by r57zone** [comment]
On slower systems (not vr ready) this makes it more slower. With updates, it is turned on by default. I updated the program SteamVR Settings and now it is turned off by default. Now it's a little faster.  
Try to download the new [SteamVR Settings](https://github.com/r57zone/OpenVR-OpenTrack/releases) and reinstall (the configuration file will be updated).

**Comment by ghost** [comment]
Thanks, will test then will let you know.
