### ISSUE TITLE
Positional Tracking

### ISSUE THREAD

**Issue by baseru** [r57zone/OpenVR-OpenTrack#2]
Can you add positional tracking and UDP Server for stream vr data?

**Comment by r57zone** [comment]
I added support for position tracking. Please check the correctness of the positional tracking sensitivity, and also whether x, y, z are being confused in the positioning.

The driver opens the UDP server 4242, you can simply send the structure to the UDP server to change the tracking or rotation values of the HMD.

C++ structure:
```
struct TOpenTrackPacket {
	double x;
	double y;
	double z;
	double yaw;
	double pitch;
	double roll;
}
```
[Example](https://github.com/r57zone/OpenTrack-UDP-receive/blob/master/ConsoleApplication1.cpp) of read data from OpenTrack (need change to send data).

Delphi stucture:
```
type TOpenTrackPacket = record
    x: double;
    y: double;
    z: double;
    yaw: double;
    pitch: double;
    roll: double;
end;
```
[Example](https://github.com/r57zone/VR-tracking-apps/tree/master/Razor%20IMU%20SteamVR) of read data from Razor IMU tracker (Arduino) and send to SteamVR driver.

**Comment by r57zone** [comment]
@umutbaser Could you test the new version?

**Comment by baseru** [comment]
I tested but there’s a strange problem if i try to use opentrack with my data opentrack is not reading my data but if i send my position and rotation data directly on 4242 Numbered port thats working clearly. Thanks a lot for helping.

**Comment by r57zone** [comment]
@umutbaser It is necessary to change the Output to UDP in OpenTrack and the IP address in the settings to 127.0.0.1.

**Comment by baseru** [comment]
Sorry i tried to say opentrack doesnt reading my values. I tried to change input port on the OpenTrack but it doesnt worked so i made a new server and i am sending the rotation data and position data directly to port:4242 and it is more better for my driver thanks for helping.
