### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by crabctrl** [r57zone/OpenVR-OpenTrack#20]
Does this support Linux, and if not, why (and when)

**Comment by r57zone** [comment]
Linux is not supported. I don’t know why to support it, because there are no games on Linux or very little.

**Comment by crabctrl** [comment]
Many SteamVR games work in SteamPlay, making this a logical option

**Comment by toby3d** [comment]
I will allow myself to return to this issue. Especially after a time in which support for the platform has become much better thanks to Proton and SteamDeck.
