### ISSUE TITLE
Compositor error when installing

### ISSUE THREAD

**Issue by plasticrafting** [r57zone/OpenVR-OpenTrack#21]
Good morning, everyone,

I have a problem with the installation of the OpenVR drivers.
When I install it with SteamVR Settings.exe and launch SteamVR, it recognizes my phone through OpenTrack, but SteamVR tells me that the compositor is not available. As soon as I uninstall the drive through SteamVR Settings.exe, SteamVR works again but no longer recognizes OpenTrack.

(SteamVR version used: 1.3.22)

Anyone have any idea how to fix this?

**Comment by r57zone** [comment]
Good morning, do you have problems with UDP driver? Try FreeTrack if you use UDP.

**Comment by plasticrafting** [comment]
I tried both FreeTrack and UDP installation, same issue for both.

**Comment by r57zone** [comment]
I checked the work with the latest SteamVR, everything works. Try to delete SteamVR and the folder "..\Steam\steamapps\common\SteamVR", then install SteamVR again. Next close Steam and SteamVR completely (you can restart your computer if you do not have it in autorun) and install the FreeTrack driver again via SteamVR Settings. Set output driver FreeTrack in OpenTrack.

**Comment by plasticrafting** [comment]
I completely uninstalled steam, reinstalled it, then installed SteamVR, turned off steam and steamvr, restarted the computer, installed the FreeTrack driver, put Freetrack in Output on OpenTrack. I have the exact same compositor problem.

**Comment by plasticrafting** [comment]
It seems that the problem comes from steamvr.vrsettings, since as soon as I restore the file by default (before installing the driver), it no longer makes the error but no longer detects opentrack.

**Comment by r57zone** [comment]
Could you post steamvr.vrsettings?

**Comment by plasticrafting** [comment]
Sorry for my late answers, i'm really busy these days.

{
   "LastKnown" : {
      "HMDModel" : "Null Model Number"
   },
   "dashboard" : {
      "enableDashboard" : false
   },
   "driver_null" : {
      "DebugMode" : false,
      "DistanceBetweenEyes" : 0,
      "DistortionK1" : 0.9100000262260437,
      "DistortionK2" : 0.93000000715255737,
      "ScreenOffsetX" : 0,
      "ZoomHeight" : 0.80000001192092896,
      "ZoomWidth" : 0.80000001192092896,
      "displayFrequency" : 60,
      "enable" : true,
      "id" : "Null Driver",
      "ipd" : 0.064999997615814209,
      "renderHeight" : 864,
      "renderWidth" : 1536,
      "secondsFromVsyncToPhotons" : 0.10000000149011612,
      "serialNumber" : "Null 4711",
      "windowHeight" : 864,
      "windowWidth" : 1536
   },
   "steamvr" : {
      "activateMultipleDrivers" : true,
      "allowAsyncReprojection" : false,
      "directMode" : false,
      "enableHomeApp" : false,
      "forcedDriver" : "null",
      "lastVersionNotice" : "1.3.22",
      "lastVersionNoticeDate" : "1555008971",
      "startMonitorFromAppLaunch" : false
   }
}

**Comment by r57zone** [comment]
The config was created without errors, it should work, I do not understand why it does not work.

**Comment by plasticrafting** [comment]
I'll try it on another PC, I'll keep you informed.

**Comment by plasticrafting** [comment]
I tried on another PC, I installed steam and steamvr, I installed the freetrack driver, and it's the same exact error. He recognizes my phone with Freepie IMU and OpenTrack, but he tells me there is a compositor problem. So I can exclude the PC from the possible causes of the problem.

**Comment by r57zone** [comment]
Try it is https://github.com/TrueOpenVR is the same, there is a FreeTrack driver.

**Comment by plasticrafting** [comment]
Exact-same-error

What I don't understand is that with TrinusVR it works, the problem with it is that the stream is seriously saturated (not a connection problem)

**Comment by r57zone** [comment]
I updated the driver, can it work now?

**Comment by plasticrafting** [comment]
Hi,

I bought a Rift S 8 months ago

**Comment by loplkc** [comment]
I am trying to get OpenTrack working with SteamVR and ran into this exact issue. My theory (based on the previous posts) is that it has something to do with an incompatibility between the OpenTrack bridge driver and the specific streaming service. I am using Radeon ReLive with an Oculus Go.

**Comment by r57zone** [comment]
I think the only problem that this might not work is the wrong setting of the resolution and coordinates of windowX, windowY or the wrong resolution, it doesn't seem to work at some resolutions (4: 3).
This is the [utility](https://www.nirsoft.net/utils/multi_monitor_tool.html) shown by windowX (Left), windowY (Top). You can also try enabling the debug mod, it might work, for a test.
