### ISSUE TITLE
Finger tracking and body part

### ISSUE THREAD

**Issue by ghost** [r57zone/OpenVR-OpenTrack#22]
Hello,

Have you found a way to send finger tracking data to SteamVR with CreateSkeletonComponent and UpdateSkeletonComponent ?

I am working with https://github.com/spayne/soft_knuckles but it doesn't work.

Else about the body part, I have absolutely no idea how vive tracker is working.

**Comment by r57zone** [comment]
Hello, there is only HMD support in this driver, there is no controllers support. I don’t know why it doesn’t work.

**Comment by ghost** [comment]
your https://github.com/r57zone/OpenVR-driver-for-DIY is working btw

It gives me two HTC vive controllers.

**Comment by r57zone** [comment]
I did controller support in other controllers [[1]](https://github.com/TrueOpenVR/SteamVR-TrueOpenVR), but valve constantly breaks compatibility, so my interest is gone.

As for knuckles, I have not tried it, I don’t know how to make support.

**Comment by ghost** [comment]
Got it
