### ISSUE TITLE
Error 422 when using OpenTrack driver

### ISSUE THREAD

**Issue by Santikun** [r57zone/OpenVR-OpenTrack#23]
Hello, I'm trying to get OpenTrack (bridged with UCR) working with SteamVR, but when I do it just gives me an error right after detecting the headset:
https://i.imgur.com/h1mbkhO.png

If I try to ignore it and open a game, I get this error instead:
https://i.imgur.com/XqjaLCc.png

I have the latest versions of SteamVR (1.11.1), OpenTrack (2.3.11), UCR (0.1.22) and the OpenVR driver. I also tried reinstalling SteamVR. Removing the OpenTrack driver from the SteamVR folder seems to fix it. What's the issue?

EDIT: I fixed this by using SteamVR Settings app. I didn't know I had to since it wasn't included in the last release, but I downloaded it from the previous and it works perfectly now. Thanks a lot for this!

**Comment by Santikun** [comment]
steamvr.settings:
> {
>    "dashboard" : {
>       "enableDashboard" : false
>    },
>    "driver_null" : {
>       "enable" : true,
>       "id" : "Null Driver",
>       "renderHeight" : 768,
>       "renderWidth" : 1280,
>       "secondsFromVsyncToPhotons" : 0.10000000149011612,
>       "serialNumber" : "Null 4711",
>       "windowHeight" : 768,
>       "windowWidth" : 1280,
>       "windowX" : 100,
>       "windowY" : 100
>    },
>    "notifications" : {
>       "DoNotDisturb" : true
>    },
>    "steamvr" : {
>       "activateMultipleDrivers" : true,
>       "directMode" : false,
>       "enableHomeApp" : false,
>       "installID" : "3064945215659698721",
>       "lastVersionNotice" : "1.10.32",
>       "lastVersionNoticeDate" : "1584997241",
>       "mirrorViewGeometry" : "0 0 960 912",
>       "startMonitorFromAppLaunch" : false
>    }
> }

**Comment by r57zone** [comment]
Hello, are you using the latest driver?
"driver_null" is no longer necessary and everything is configured in "...\Steam\steamapps\common\SteamVR\drivers\opentrack\resources\settings\default.vrsettings". "driver_null" must be removed from "steamvr.settings:" so that it does not interfere.
steamvr.settings
```
{
"dashboard" : {
"enableDashboard" : false
},
"notifications" : {
"DoNotDisturb" : true
},
"steamvr" : {
"activateMultipleDrivers" : true,
"directMode" : false,
"enableHomeApp" : false,
"installID" : "3064945215659698721",
"lastVersionNotice" : "1.10.32",
"lastVersionNoticeDate" : "1584997241",
"mirrorViewGeometry" : "0 0 960 912",
"startMonitorFromAppLaunch" : false
}
}
```
default.vrsettings
```
{
   "opentrack" : {
      "DebugMode" : false,
      "DistanceBetweenEyes" : 0,
      "DistortionK1" : 0.91,
      "DistortionK2" : 0.93,
      "ScreenOffsetX" : 0,
      "ZoomHeight" : 0.8,
      "ZoomWidth" : 0.8,
      "displayFrequency" : 60,
      "renderHeight" : 1080,
      "renderWidth" : 1920,
      "secondsFromVsyncToPhotons" : 0.004999999888241291,
      "serialNumber" : "1001",
      "windowHeight" : 1080,
      "windowWidth" : 1920,
      "windowX" : 0,
      "windowY" : 0
   }
}
```
"windowHeight" and "windowWidth" need to change according to the resolution of your monitor. What other parameters mean you can read here - https://github.com/r57zone/OpenVR-OpenTrack/blob/master/README.md#configuration-file-options
If your monitor is 1280 by 768, then replace 1920 with 1280 and 1080 with 768.
