### ISSUE TITLE
SteamVR crashes upon start due to compositor error

### ISSUE THREAD

**Issue by loplkc** [r57zone/OpenVR-OpenTrack#25]
When I start SteamVR, it fails with the error code "VRInitError_IPC_CompositorConnectFailed: 'Shared IPC Compositor Connect Failed (306)'". I am using the Razer Hydra SteamVR driver for controllers and Radeon ReLive to stream video to an Oculus Go. I do not know if any of these are the cause of the issue. The only way to prevent the crash that I have found is to remove the opentrack folder from the drivers folder entirely.

**Comment by r57zone** [comment]
What is your monitor resolution? How many monitors? Which driver are you using FreeTrack or UDP?

I think the only problem that this might not work is the wrong setting of the resolution and coordinates of windowX, windowY or the wrong resolution, it doesn't seem to work at some resolutions (4: 3).

This is the [utility](https://www.nirsoft.net/utils/multi_monitor_tool.html) shown by windowX (Left), windowY (Top).

You can also try enabling the debug mode, it might work, for a test.

To use more than 1 driver in SteamVR, you need to [enable the activateMultipleDrivers **option**](https://github.com/r57zone/Razer-Hydra-SteamVR-driver#installation).

**Comment by loplkc** [comment]
Sorry for the extremely late response. I looked through some of the closed issues (which I stupidly didn't notice were there) and found a post addressing the SteamVR Settings application. After downloading it from an earlier release and using it, the crash did not occur and the video was displayed on the monitor properly. However, I ran into some new problems:

- The feed did not stream to my headset. My goal is not to display the video on my monitor; I am trying to use Radeon ReLive with my Oculus Go. What can I change to make ReLive work properly instead?
- The tracking was not usable. I was using a moderately large aruco tracker taped to the front of my headset, and the tracking was jittery and did not rotate on the correct axes when I turned it. The maximum angles at which I could rotate my headset without losing tracking were also very limited. Even if I can fix the axis issues, it seems like the others are inherent to the tracking method, and it is my mistake for expecting a paper tracker to work perfectly. Which tracking method would you recommend for VR games?

Thank you for your patience.

**Comment by loplkc** [comment]
So I found a [program](https://github.com/sheepsskullcity/opentrackkinect) that lets me use my Kinect 360 to do positional tracking with OpenTrack. Is there any way to use this with the rotational data sent from Radeon ReLive, or is this not practical?

Also, I've noticed that ReLive does not work after using the SteamVR Settings application, and using it to uninstall the settings allows ReLive to work again.

**Comment by r57zone** [comment]
This driver does not support changing the position of other drivers. You probably already have a different driver in use, so there is a driver conflict.

Unfortunately, reading from Radeon ReLive is not supported.

If you only need to add positioning to Oculus Go, then the Driver4VR project may be suitable for you, it seems it supports changing tracking on other devices.

Also, I would like to note that I played several games in VR, as a rule, positioning of the hmd is not required.
