### ISSUE TITLE
Error 422.

### ISSUE THREAD

**Issue by notsatvrn** [r57zone/OpenVR-OpenTrack#27]
Only occurs when OpenTrack driver is installed.

I've tried both the FreeTrack and UDP versions.

SteamVR Version: 1.17.16

OpenVR-OpenTrack Version: 0.9

OpenTrack Version: 2.3.13

**Comment by notsatvrn** [comment]
After further investigation, it appears your driver just needs to be updated to OpenVR SDK 1.16.8.

**Comment by r57zone** [comment]
![изображение](https://user-images.githubusercontent.com/9499881/124349363-bc772380-dbff-11eb-83c7-3e8a42badb06.png)
You have an error in your config file. You need to set the correct screen resolution
