### ISSUE TITLE
Question: Does the VRCompositor Window need to be open for the rendering to continue?

### ISSUE THREAD

**Issue by zinixyt** [r57zone/OpenVR-OpenTrack#29]
Hi, I have a small problem.
Whenever I click on another window than the VRCompositor, it stops rendering new frames but the Head still moves.

I am using the FreeTrack driver, what should I change for this to work?
Currently testing this with Assetto Corsa, when I click on assetto corsa to move the cursor, the rendering catches up with the head rotation but seems like SteamVR doesn't recognize the head movement to generate new frames, kinda like you have a picture stuck to your face but the borders flicker.

EDIT: I will try to record a video of this happening.

----------------------------------------------------------
THE FIX: When the problem starts to appear, click at least once on the "Headset Monitor" window. You should be good for some time.
----------------------------------------------------------

Is there a fix? Or should I be using a different driver?

PS: Sometimes the whole PC freezes when I click on either the VRCompositor window or the game window.
Thanks,
Zinix

**Comment by r57zone** [comment]
Hello, if the picture does not keep up with the image in VR, then either the debug mode is enabled, or the GPU performance is not enough.

**Comment by zinixyt** [comment]
I don't think you got the message right, it's my fault. I will try to get a video recorded about this as soon as possible. Currently having some issues with a PlayStation Move camera.

**Comment by zinixyt** [comment]
Alright, so I've got footage of the problem. The first part is The problem I have, and second part (after the black screen) is the driver functioning perfectly (dont mind the performance issues, my pc doesn't handle recording very well). The problem happens when the VRCompositor window isn't focused.

I have attached a video.

https://user-images.githubusercontent.com/44553085/215458486-0916ce6b-1485-4e13-836f-633720befdf6.mp4

**Comment by r57zone** [comment]
Is DebugMode turned off in the config file?
I see that the bar is red, it means that the GPU is not recovering from the load.
What video card do you have? Maybe you should lower renderWidth, renderHeight, to 720 by 720 or lower.

**Comment by zinixyt** [comment]
I would say the most important part of the video is the first part (before the black screen). I have never had any performance problem. I have a GTX 1060 3GB. And yes, debug mode is turned off.

EDIT: Here's the steamvr performance test results.
![image](https://user-images.githubusercontent.com/44553085/215462394-ef7cdb10-4f28-4fcf-8eef-94b8113bc078.png)

**Comment by r57zone** [comment]
https://github.com/r57zone/OpenVR-OpenTrack/releases/download/1.0/SteamVR.OpenTrack.UDP.1.0.zip
Try a driver with UDP support, change Output to UDP and change its address to 127.0.0.1, will that help?

**Comment by zinixyt** [comment]
Yes, It worked!!

You should probably add this to the documentation. Although you only have to click one time in the window, from then on, it works fine!
