### ISSUE TITLE
Image Distortion

### ISSUE THREAD

**Issue by ghost** [r57zone/OpenVR-OpenTrack#3]
Hi is there a way to implement image distortion with your drivers?

**Comment by r57zone** [comment]
I changed the test sample driver, which apparently does not support the distortion.

**Comment by ghost** [comment]
I found this https://github.com/burrito82/spvr.control
It seems to have distortion implemented on it, is there a way to port it to your code?

**Comment by r57zone** [comment]
Probably not, sorry. Maybe someone else will be interested.

**Comment by r57zone** [comment]
https://github.com/ValveSoftware/openvr/issues/305

**Comment by r57zone** [comment]
Added distortion. Parameters can be changed after installation in the file "steamvr.vrsettings". Two constants for distortion and 2 constants ZoomWidth, ZoomHeight.
