### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by deggial2005** [r57zone/OpenVR-OpenTrack#4]
Hello and thanks for your work.
It seems that it doesn't work anymore with the newest steamvr beta updates. Do you plan a fix?
I hope I am wrong but can't get tracking to work anymore.
Thank you again

**Comment by r57zone** [comment]
I will check in the near time.

**Comment by r57zone** [comment]
I checked on the latest beta SteamVR. Everything is working. Replace the null driver folder again (it is sometimes replaced by an update).

**Comment by r57zone** [comment]
Try the application "[SteamVR Settings](https://github.com/r57zone/OpenVR-OpenTrack/releases)", it will help to properly configure SteamVR and copy the driver.
