### ISSUE TITLE
Extended mode impossible?

### ISSUE THREAD

**Issue by deggial2005** [r57zone/OpenVR-OpenTrack#5]
Hello again. I cannot seem to obtain extended mode anymore. It works before replacing the driver, with the original one. After replacing, I couldn't find a  way to get it out of direct mode. Do you know any workaround? It worked before latest SteamVR updates.

**Comment by r57zone** [comment]
Do you display a picture on your first monitor?

**Comment by deggial2005** [comment]
I am using <"windowX" : 1920> in steamvr.vrsettings so the compositor goes in the extended monitor (hmd). The issue is with fullscreen option in games. The gpu is on crack and it tries to show 2 x fullscreen at once, severely chopping the game's framrate to 4-8 FPS. That's where I realized the compositor is running in "fullscreen". I can make it extended if I use the original null driver, but not with yours :). 

Here is the settings file (added .txt for uploading)
[steamvr.vrsettings.txt](https://github.com/r57zone/OpenVR-OpenTrack/files/1395439/steamvr.vrsettings.txt)

No matter what I do, I can get no extended mode (which behaved as a borderless windowed application so far).
Thank you.

P.S. : I had no idea where your question points, so I tried to describe the actual behaviour. However, while the compositor runs on the 2nd monitor, I can use see the desktop, but without "allowAsyncReprojection" checked, the compositor goes black as soon as I click something outside.

P.S. 2: I use 1920x900 in order to correct the aspect ratio. I created a custom centered resolution for my 1080p HMD.

**Comment by r57zone** [comment]
I updated driver to latest SDK, try the [new version](https://github.com/r57zone/OpenVR-OpenTrack/releases).

**Comment by deggial2005** [comment]
God you're fast :)
I'll try it as soon as I get home

**Comment by deggial2005** [comment]
well no changes for me...maybe there are other causes, because it was working well before. Thanks for your fast responses

**Comment by r57zone** [comment]
Try the application "[SteamVR Settings](https://github.com/r57zone/OpenVR-OpenTrack/releases)", it will help to properly configure SteamVR and copy the driver.

**Comment by deggial2005** [comment]
Sorry to come back on this issue. No matter what I do, once I replace the original driver with your driver I can't get the extended mode working.
The behavior is as in direct mode: once it looses focus, the compositor turns red (tracking works).
I just uninstalled SteamVR, erased the remaining install folder. Installed again, used "_SteamVR Settings_" app. It looks like the driver just cannot follow _"directMode" : false_
The original null driver works like a charm in extended mode :/

**Comment by r57zone** [comment]
@deggial2005 Have you tried setting with "SteamVR Settings"? Works only in full screen mode. You can configure the secondary monitor through the program.

Also can adjust lens distortion. Can this help you? You can change the ZoomWidth and ZoomHeight lenses and thereby change the aspect ratio.

Extended Mode did you mean Window Mode? The window mode is locked at 30 FPS, because of the lock it is impossible to use.

**Comment by deggial2005** [comment]
Solved! Thank you for the zoom settings!
The red screen was because the game window was slightly overlapping the compositor in the extended display.

Oh boy! This 0.5.1 is the Holy Grail for DIY headset. By altering the zoom settings, not only I could change the aspect ratio, but also the FOV by keeping a constant zoom ratio (!!!). This is now exactly what my HMD needed.

You are the man! Cheers
