### ISSUE TITLE
Can't make it run

### ISSUE THREAD

**Issue by andrewpros** [r57zone/OpenVR-OpenTrack#6]
No matter what i do i always get the same error https://i.imgur.com/6bEerX7.png

As soon as i replace null driver i get this error, tried freetrack or only UDP, still the same, if i replace back the original steam null driver it works immediately.
If have checked steam vr stable, beta, the same result.

Don't know what to do.

**Comment by r57zone** [comment]
Send your "steamvr.vrsettings".

**Comment by andrewpros** [comment]
{
   "dashboard" : {
      "enableDashboard" : false
   },
   "driver_null" : {
      "enable" : true,
      "id" : "Null Driver",
      "renderHeight" : 768,
      "renderWidth" : 1280,
      "secondsFromVsyncToPhotons" : 0.10000000149011612,
      "serialNumber" : "Null 4711",
      "windowHeight" : 768,
      "windowWidth" : 1280,
      "windowX" : 100,
      "windowY" : 100
   },
   "notifications" : {
      "DoNotDisturb" : true
   },
   "steamvr" : {
      "activateMultipleDrivers" : true,
      "directMode" : false,
      "enableHomeApp" : false,
      "mirrorViewGeometry" : "0 0 960 912",
      "startMonitorFromAppLaunch" : false
   }
}

**Comment by r57zone** [comment]
WindowX and WindowY change to 0.

**Comment by andrewpros** [comment]
Well something happened, this driver runs, but in fullscreen and i see only a light gray/blue background steam vr standard null driver preview, not even the grid, i would made a screenshot but if i do it turn red, if i alt tab to desktop, vr status windows says that the headset is connected but not delivering tracking data.

**Comment by r57zone** [comment]
Are you using on the second monitor?
You changed WindowX and WindowY to 0 in first driver?

**Comment by andrewpros** [comment]
No, it is a single monitor, i have also connected tv by hdmi but i disconnected it to be 100% sure it is not that.
I copied steamvr.vrsettings from udp driver package, so it is as it should be.

**Comment by r57zone** [comment]
Change the WindowHeight, WindowWidth, RenderHeight, RenderWidth parameters for you resolution monitor.

**Comment by andrewpros** [comment]
Already done that, still the same if i copy back original null driver dll it works.

**Comment by r57zone** [comment]
Try the application "[SteamVR Settings](https://github.com/r57zone/OpenVR-OpenTrack/releases)", it will help to properly configure SteamVR and copy the driver.

**Comment by andrewpros** [comment]
I will pass, i have properly configured steamvr and the driver is where it should, so this is not a problem in my config or driver file in the wrong place.

**Comment by r57zone** [comment]
I recompiled the drivers, try new drivers.

**Comment by andrewpros** [comment]
Odd thing i checked the new udp driver, the same issue, so i checked that new application (udp also), done apply, now it runs still in fullscreen but at least i see the grid so i can control it by phone and see the results.

The odd thing is, the steamvr.settings and the driver file is the same as it was, the same content.

**Comment by deggial2005** [comment]
I would uninstall, erase the folder then a clean install. Because it works

**Comment by andrewpros** [comment]
Should it be always fullscreen? I played a lot with riftcat and steam games and it was always window.
I even downloaded the driver source and compiled it myself, to try to find any reason, but had no time to test it yet.

**Comment by r57zone** [comment]
@andrewpros Yes unfortunately the source driver works only in fullscreen, otherwise it is locked to 30 FPS.

You can streaming fullscreen picture with "Moonlight" and "Nvidia Geforce Experience" (if use Nvidia GPU).

**Comment by andrewpros** [comment]
That cant be true, the original null driver sample always runs in window. I will check it further.

**Comment by r57zone** [comment]
You can start it with lock to 30 FPS. If you start with Fraps or MSI Afterburner apps, you will see lock at 30 FPS.

**Comment by andrewpros** [comment]
Then how steamvr know it is a null driver, if null driver is locked 30fps, other 3rd party software/hardware driver would too, i need to check it myself.
