### ISSUE TITLE
Controller data by UDP

### ISSUE THREAD

**Issue by jelle284** [r57zone/OpenVR-OpenTrack#7]
Hi.
Is it possible to send x-y-z-yaw-pitch-roll for two controllers over UDP and have them recognised as eg. 2 vive controllers?
Possibly button presses as well

**Comment by r57zone** [comment]
Hello, on this driver (Valve driver sample with small fixes) implements rotation and position only for HMD.
I created a [feature request](https://github.com/ValveSoftware/openvr/issues/624) with asking to create the same driver for the controllers. If they implement it, I will make support OpenTrack and FreeTrack.

**Comment by jelle284** [comment]
Thanks for the reply.
Lens distortion in the new version is great by the way

**Comment by r57zone** [comment]
I did this in [TrueOpenVR](https://github.com/TrueOpenVR). Can control the controllers using the Xbox gamepad, using the keyboard, Arduino and Android phone.
