### ISSUE TITLE
Compositor not available Error 400

### ISSUE THREAD

**Issue by mikemac30** [r57zone/OpenVR-OpenTrack#8]
SteamVR home does not launch and it says the headset is connected but also says "Compositor not available" It must be your program because I reinstalled SteamVR and then started it up and it worked but after running your program it went back to giving the error.

**Comment by r57zone** [comment]
Try changing the properties SteamVR -> beta version -> OpenVR-Input Emulator-temporary properties. Then install the driver again.

**Comment by mikemac30** [comment]
It Worked! Thanks a billion! Awesome tool ya got here.

**Comment by r57zone** [comment]
Also, the full remove of SteamVR (from Steam and SteamVR folder in "..\Steam\steamapps\common") and then a install SteamVR without after change channel update (beta or etc) can help. This helped for me.
